### ISSUE TITLE
部分邮箱编码错误,发送的地址是多个会报错

### ISSUE THREAD

**Issue by userQue** [huyinghuan/mail#1]
需要在hesder里面添加发送主题和内容的编码。
func (sender *MailSender) SendMail(subject string, content string, contact []string)
这个方法的参数contact是多个的时候无法通过校验，需要处理。

**Comment by huyinghuan** [comment]
修复多联系人bug: f33cc1d

**Comment by huyinghuan** [comment]
增加 header 头设置 08c9687  ，具体见 `sender_test.go`
